### PR TITLE
Exposing API AddImageShapeCompatibilityEntry.

### PR DESCRIPTION
**Pull request by buccarel**
Signed-off-by: Mattia Buccarella <m.buccarella@gmail.com>

### CODE REVIEW

**Comment by jodoglevy** [comment]
Thanks @buccarel for this. However, the file you've changed is actually a generated file, and so if we merge this in, the change will get overwritten the next time we generate image operations.

I'm reaching out internally to the team that owns this operation to see if they can get it into the SDK generation pipeline. In the meantime, you can use a local version of the SDK with your change, or the [raw request signer](https://docs.cloud.oracle.com/iaas/tools/ruby/latest/index.html#label-Signing+a+Raw+Request) in the Ruby SDK.

**Comment by buccarel** [comment]
Hi,

ok, this is interesting. So, I think I missed the fact that the file is generated. Where do I figure it out from? I don't think I saw anything about it in the file. Also what's the right place to contribute to that API?

Thanks,
Mattia.

**Comment by andy-miles** [comment]
Since this is generated code, I filed a request with the Compute team to review adding this API to the SDK.

**Comment by jodoglevy** [comment]
This feature is now in the Ruby SDK: https://github.com/oracle/oci-ruby-sdk/releases/tag/v2.7.0

Closing this

**Pull request closed without merging**
