### PR TITLE
Use Ruby autoload to lower memory usage and load times 

### LINKED ISSUE #63: SDK loading time is too long
I have tried to use SDK in Functions service and found that SDK loading takes too much time. This way just `require "oci"` leads to 
> "Function did not respond within its configured timeout or within the platform max timeout."
error. The ruby version of sdk takes significally much more time than python version, this is strange.
After some investigation I have found:

1. [Place 1](https://github.com/oracle/oci-ruby-sdk/blob/master/lib/oci/auth/signers/resource_principal_token_path_provider/imds_rpt_path_provider.rb#L4)
2. [Place 2](https://github.com/oracle/oci-ruby-sdk/blob/master/lib/oci/auth/signers/resource_principal_token_path_provider/default_rpt_path_provider.rb#L4)

It is not clear why this files requiring whole SDK, I think this is a mistake.

The other thing I have found is that there is no module provided, which includes all dependencies needed for API requests signing. The only way is to require whole `"oci"` file. I have created a workaround, which works in my case ([code](https://github.com/AskarZinurov/oci-ruby-sdk/commit/ecd8e03f9b747c872cafcccdcbdf580001763e97)) but better to have something similar in sdk repo. This helps to reduce SDK loading time and allows to require it "modular" way.

Maybe not related, but I sometimes meet the 

> "/usr/lib/ruby/gems/gems/oci-2.15.0/lib/oci/auth/util.rb:62:in `initialize': Neither PUB key nor PRIV key: not enough data (OpenSSL::PKey::RSAError)"

when I trying to load secrets via SDK signed by `EphemeralResourcePrincipalsSigner` outside of Function handler. I have checked the all [variables](https://github.com/oracle/oci-ruby-sdk/blob/master/lib/oci/auth/signers/resource_principals_signer.rb#L11-L17) are in place. Maybe certificates generating takes some time and I cannot be guaranteed that they be ready on cold function start? Or maybe I missed something?

Thank you for your work guys, it is really pleasure to use ruby with Oracle cloud!

### PR DESCRIPTION
**Pull request by Fryguy**
Fixes https://github.com/oracle/oci-ruby-sdk/issues/63

Some performance numbers (on my Mac)

Before:
  Time for `require "oci"`: ~7.98s
  Memory Usage: ~282MB

After:
  Time for `require "oci"`: ~0.15s
  Memory Usage: ~6MB

  As we load the constants one-by-one memory will approach the Before
  numbers, but it will be on-demand, and most people won't use all of
  the constants.

  Constant                     | Memory (MB)   | Time to require (s)
  ---------------------------- | ------------- | -----------------------
  Response                     | 35.3203125    | 1.00000761449337e-06
  Waiter                       | 35.3203125    | 1.00000761449337e-06
  Config                       | 35.3203125    | 1.00000761449337e-06
  ResponseHeaders              | 35.3203125    | 0.0
  AiAnomalyDetection           | 38.23046875   | 0.06656299997121096
  AiLanguage                   | 39.75         | 0.03197299991734326
  AiVision                     | 41.91015625   | 0.08492200006730855
  Analytics                    | 42.9140625    | 0.032507000025361776
  AnnouncementsService         | 43.8984375    | 0.02724800002761185
  Apigateway                   | 47.3828125    | 0.1102690000552684
  ApmConfig                    | 47.75390625   | 0.024326000129804015
  ApmControlPlane              | 48.33984375   | 0.02898599999025464
  ApmSynthetics                | 50.19921875   | 0.04395399987697601
  InvalidConfigError           | 50.19921875   | 1.00000761449337e-06
  ApmTraces                    | 51.3515625    | 0.023328999988734722
  AppmgmtControl               | 52.046875     | 0.015361000085249543
  Artifacts                    | 54.8125       | 0.04081199993379414
  ApplicationMigration         | 56.44140625   | 0.04846499999985099
  Auth                         | 58.08984375   | 0.0906360000371933
  Autoscaling                  | 59.953125     | 0.029858999885618687
  Bastion                      | 60.65234375   | 0.027375000063329935
  Bds                          | 62.78515625   | 0.04873099992983043
  Blockchain                   | 64.08203125   | 0.0412619998678565
  Audit                        | 64.390625     | 0.011440000031143427
  Budget                       | 64.75         | 0.01641299994662404
  CertificatesManagement       | 67.1875       | 0.06650499999523163
  Cims                         | 67.78125      | 0.04777499986812472
  Certificates                 | 68.02734375   | 0.01834899978712201
  CloudGuard                   | 79.61328125   | 0.18001100001856685
  ComputeInstanceAgent         | 80.1875       | 0.030891000060364604
  ContainerEngine              | 81.58203125   | 0.05135999992489815
  DataCatalog                  | 90.69140625   | 0.20119499997235835
  DataFlow                     | 91.84765625   | 0.0401099999435246
  DashboardService             | 92.39453125   | 0.018493999959900975
  DataIntegration              | 113.35546875  | 0.4790139999240637
  ApiClientProxySettings       | 113.35546875  | 1.00000761449337e-06
  DataLabelingServiceDataplane | 114.34375     | 0.04453300009481609
  Signer                       | 114.34375     | 1.9997823983430862e-06
  BaseSigner                   | 114.34375     | 0.0
  DataSafe                     | 127.23046875  | 0.3338339999318123
  DataLabelingService          | 127.8515625   | 0.040151000022888184
  Database                     | 151.42578125  | 0.3798660000320524
  ConfigFileLoader             | 151.42578125  | 1.9997823983430862e-06
  DataScience                  | 156.50390625  | 0.06002699979580939
  DatabaseTools                | 158.6484375   | 0.05188699997961521
  DatabaseManagement           | 169.234375    | 0.1630639999639243
  DatabaseMigration            | 172.90625     | 0.10021200007759035
  Dts                          | 174.06640625  | 0.04579200013540685
  Devops                       | 184.8046875   | 0.29306999989785254
  Dns                          | 186.8359375   | 0.09507300006225705
  FileStorage                  | 187.31640625  | 0.03825700003653765
  Email                        | 188.484375    | 0.0521609999705106
  Events                       | 189.08984375  | 0.025058000115677714
  GoldenGate                   | 192.11328125  | 0.05926400003954768
  Functions                    | 192.99609375  | 0.014536000089719892
  Internal                     | 192.99609375  | 2.00001522898674e-06
  Jms                          | 194.96875     | 0.02924400009214878
  Healthchecks                 | 196.54296875  | 0.023825999815016985
  Identity                     | 205.53125     | 0.11686299997381866
  GenericArtifactsContent      | 205.734375    | 0.002474999986588955
  Integration                  | 207.03125     | 0.01730800000950694
  Limits                       | 207.83203125  | 0.008967000059783459
  Logging                      | 210.375       | 0.06487000011838973
  IdentityDataPlane            | 211.796875    | 0.03468800010159612
  Loggingsearch                | 211.85546875  | 0.0047790000680834055
  LoadBalancer                 | 215.40625     | 0.07779400004073977
  LogAnalytics                 | 229.86328125  | 0.28742199996486306
  KeyManagement                | 230.95703125  | 0.046907999785616994
  Mysql                        | 233.51171875  | 0.0946440000552684
  Marketplace                  | 235.14453125  | 0.05817599990405142
  Monitoring                   | 235.875       | 0.02425199979916215
  ManagementDashboard          | 236.7265625   | 0.02974899997934699
  Oce                          | 237.26953125  | 0.017729999963194132
  Ocvp                         | 238.67578125  | 0.03508600010536611
  Oda                          | 239.34765625  | 0.015342000173404813
  NetworkLoadBalancer          | 241.4296875   | 0.06582200014963746
  Nosql                        | 242.234375    | 0.03691700007766485
  Loggingingestion             | 242.29296875  | 0.004342000000178814
  Ons                          | 242.83984375  | 0.018561000004410744
  ManagementAgent              | 243.625       | 0.03671300015412271
  Opsi                         | 250.13671875  | 0.33407599991187453
  ObjectStorage                | 252.30859375  | 0.08742800005711615
  OperatorAccessControl        | 253.46875     | 0.04506599996238947
  OspGateway                   | 254.5859375   | 0.06059899996034801
  Optimizer                    | 256.87109375  | 0.10857899999246001
  OsManagement                 | 261.72265625  | 0.10402400000020862
  OsubSubscription             | 262.4375      | 0.013662999961525202
  Retry                        | 262.4375      | 2.00001522898674e-06
  OsubOrganizationSubscription | 262.515625    | 0.0029570001643151045
  ResourceSearch               | 262.9375      | 0.00822600000537932
  OsubUsage                    | 263.6171875   | 0.008076000027358532
  OsubBillingSchedule          | 263.79296875  | 0.0034089998807758093
  Sch                          | 265.73828125  | 0.033961000153794885
  Secrets                      | 265.92578125  | 0.005679000169038773
  Rover                        | 268.546875    | 0.03721199999563396
  ResourceManager              | 276.3359375   | 0.10694599989801645
  Streaming                    | 278.23046875  | 0.03486799984239042
  ServiceCatalog               | 279.875       | 0.04189700004644692
  ServiceManagerProxy          | 280.24609375  | 0.00799200008623302
  Usage                        | 280.65234375  | 0.011460999958217144
  TenantManagerControlPlane    | 284.4921875   | 0.07978799985721707
  ThreatIntelligence           | 285.29296875  | 0.01712600002065301
  VisualBuilder                | 286.6640625   | 0.02650200016796589
  UsageApi                     | 287.7890625   | 0.02395299985073507
  Vault                        | 288.8984375   | 0.01913499995134771
  Waf                          | 291.36328125  | 0.06727300002239645
  VulnerabilityScanning        | 295.9140625   | 0.10620300006121397
  ApiClient                    | 295.9140625   | 2.00001522898674e-06
  WorkRequests                 | 296.14453125  | 0.006391000002622604
  Waas                         | 299.81640625  | 0.09920800011605024
  Regions                      | 299.81640625  | 2.00001522898674e-06
  Core                         | 318.42578125  | 0.5568480000365525
  VERSION                      | 318.42578125  | 2.00001522898674e-06
  Errors                       | 318.42578125  | 1.00000761449337e-06
  ObjectStorage::Transfer      | 318.4609375   | 0.007651000050827861

### CODE REVIEW

**Comment by Fryguy** [comment]
Scripts used the generate the table, if you're curious:

```
gem install get_process_mem

$ irb -I lib
>> require "get_process_mem"; require "benchmark"
=> true
>> GetProcessMem.new.mb
=> 29.87109375
>> Benchmark.realtime { require "oci" }
=> 0.12123499996960163
>> GetProcessMem.new.mb
=> 35.78125
>> OCI.constants.each { |c| t = Benchmark.realtime { OCI.const_get(c) }; puts "#{c}\t#{GetProcessMem.new.mb}\t#{t}" }; nil
...
```

**Comment by Fryguy** [comment]
Bump.  @ZiyaoQiao can you take a look?

**Comment by Fryguy** [comment]
Bump.  Not sure if @ZiyaoQiao is the right person to ping.  If not, can you ping someone who can take a look?

**Comment by ZiyaoQiao** [comment]
@Fryguy Hi, thanks for providing this pr. We'll work on this in the coming weeks.

**Comment by Fryguy** [comment]
@ZiyaoQiao Out of curiosity are you using the OpenApiGenerator to generate this gem?  If so, there was an issue recently opened there requesting support for autoload.

**Comment by Fryguy** [comment]
@ZiyaoQiao Any updates here?

Note that I recently put a similar change into a similar client gem that is working nicely.  See https://github.com/xlab-si/intersight-sdk-ruby/issues/13

**Comment by ZiyaoQiao** [comment]
@Fryguy Thanks for sharing this. These changes are included in 2.18.0 OCI Ruby SDK and because we're using swagger code generator for generating these codes, we can't merge in this pr and had to fix it internally. Sorry about this and thank you again for sharing this approach!

**Comment by Fryguy** [comment]
@ZiyaoQiao Not a problem, and I understand.  For what it's worth, I'm working on trying to get this into the official openapi-generator here: https://github.com/OpenAPITools/openapi-generator/pull/12680

**Pull request closed without merging**
